name: Nuisance
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-learn=1.7.*
  - matplotlib=3.10.*
  - scipy=1.15.*
  - pandas=2.3.*
  - tqdm
  - pyyaml>=5.4.1
  - json5
  - cython
  - statsmodels
  - pip:
      - numpy<2.0
      - faiss-cpu
      - libmr
      - opencv-python
      - imgaug>=0.4.0
      - timm>=1.0.11
      - foolbox>=3.3
      - gdown
      - diffdist>=0.1
      - git+https://github.com/Jingkang50/OpenOOD --no-deps
